### ISSUE TITLE
Submit changes upstream?

### ISSUE THREAD

**Issue by traversaro** [robotology-dependencies/qpOASES#1]
@francesco-romano I guess you are not planning to add cmake support for building other bindings, so I guess we can go on and submit our modification upstream (better rpath support and matlab bindings compiled in cmake) so we can drop this fork.

**Comment by francesco-romano** [comment]
I was unsure about simulink bindings support. Right now I found them quite unnecessary (at least for us).

About the matlab binding: they should be tested on old cmake  (do you remember the issue of @rlober ?)

**Comment by traversaro** [comment]
I would simply drop the simulink binding compilation for the moment if we are not so sure, we can always submit it upstream later. The problem of @rlober was with CMake 2.8.11 ?

**Comment by francesco-romano** [comment]
Yes if I remember correctly. 
I changed the cmake file, but I'd never had the chance to test it again.

**Comment by francesco-romano** [comment]
@traversaro 
I finished updating the CMakeFiles. 
I don't know if you want to submit the changes upstream.
I'd not delete this repository anyway (maybe we can update it as soon as they do the release).
I still have to clean up the compilation options, but this will be a long term task (as soon as I start work seriously on the lib)

**Comment by traversaro** [comment]
I forgot this thing even existed, and it is actually super-important for us. : ) 
I'll need to open an issue somewhere more visibile.

**Comment by traversaro** [comment]
cc @S-Dafarra @gabrielenava

**Comment by traversaro** [comment]
As we dropped the use of qpOASES matlab bindings (see https://github.com/robotology/robotology-superbuild/pull/613) the only changes that are interesting to submit upstream and to switch using the upstream once accepted are:
* https://github.com/coin-or/qpOASES/pull/108
* https://github.com/coin-or/qpOASES/pull/109

As this have been submitted, I think we can close the issue.
