### ISSUE TITLE
Move repository to robotology-dependencies

### ISSUE THREAD

**Issue by drdanz** [robotology-dependencies/qpOASES#2]
As discussed with @traversaro, this repository should be moved to [robotology-dependencies](https://github.com/robotology-dependencies)

cc-issue: robotology/robotology.github.io#2

**Comment by drdanz** [comment]
@traversaro Is it ok to move this as previously discussed?
Also let me know which users should have access to this repo.

**Comment by drdanz** [comment]
Duplicate of #7

**Comment by traversaro** [comment]
Ok, and give access to me and @francesco-romano .

**Comment by drdanz** [comment]
Done

cc-issue: robotology/robotology.github.io#2
